# Generated by Django 2.1.7 on 2019-04-29 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
